"""Loader for this project's persisted QML reduced states.

These are NOT synthetic: they are the real rho_A before/after the
ZZ-null-unitary intervention, for the 10 trained classifiers (5 MNIST
seeds + 5 BloodMNIST seeds) whose reduced states are used throughout
this repository's experiments. Generated by the state-generation
training pipeline (theta reconstruction and re-derivation is covered
by manifold/theta_jacobian.py).

This module only reads the .npz files; it does not regenerate them.
"""
from dataclasses import dataclass
from pathlib import Path

import numpy as np

DEFAULT_SAVE_DIR = (
    Path(__file__).resolve().parents[1] / "data" / "saved_states"
)


@dataclass
class QmlState:
    state_id: str
    dataset: str          # "mnist" or "bloodmnist"
    seed: int
    stage: str             # "before" or "after"
    a: int                 # target-subsystem qubit count
    rho: np.ndarray         # (2^a, 2^a) complex density matrix
    final_ca: float
    d_true_entropy: float   # the pre-computed S(rho_A), cross-check


def load_qml_states(save_dir: Path = DEFAULT_SAVE_DIR) -> list:
    if not save_dir.exists():
        raise FileNotFoundError(
            f"{save_dir} not found -- the data/saved_states directory is required "
            "for the real-state experiment."
        )

    states = []
    for fn in sorted(save_dir.glob("*.npz")):
        dataset, seed_str = fn.stem.split("_seed")
        seed = int(seed_str)
        d = np.load(fn, allow_pickle=True)
        a = int(d["n_a"])
        final_ca = float(d["final_ca"])
        for stage in ("before", "after"):
            rho = d[f"rho_{stage}"]
            d_true = float(d[f"D_true_{stage}"])
            states.append(QmlState(
                state_id=f"{dataset}_seed{seed}_{stage}",
                dataset=dataset, seed=seed, stage=stage, a=a,
                rho=rho, final_ca=final_ca, d_true_entropy=d_true,
            ))
    return states
